### PR TITLE
WIP on Typescript

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
### Goal of the Draft PR
This is a draft on moving the Rive file into Typescript.
The goal of this draft was to get more acquainted with the code. I figured out it could be useful to be shared. Happy to close it if this is already an ongoing work on your side

### The current stat
There is still many errors in to file, and missing types. 
I tried to keep the code as close as possible to the rive.js is currently, I mainly : 
- transformed Rive into a class
- add "private" keyword for method with "_"
- add types
- change self by this

### Future work
There is still some work I would like to do to deliver an error-free file: 
- import missing types from rive-canvas somehow.
- create a `getEvent(name)` method to fix missing typings.

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
- For typing reasons I moved each event property into a record and created a private `getEvents(name)` methods.
- I put `any` for types coming from `rive-canvas` for now.
- Remaining errors come from import/export

**Comment by mjohnsullivan** [comment]
Thank you for starting to do this, but we're in the middle of doing much the same task at the moment.

I'd suggest you pause this for the moment while we finish the first pass and then we can review?

**Comment by GrandSchtroumpf** [comment]
sure, no problem :)

**Comment by mjohnsullivan** [comment]
And thank you again for starting this; it's great to have more input on our Typescript conversion.

**Pull request closed without merging**
