### PR TITLE
Revert back to skia_rive_optimized for wasm

### PR DESCRIPTION
**Pull request by csmartdalton**

### CODE REVIEW

**Comment by luigi-rosso** [comment]
Looks like the versions aren't compatible, we must've updated some includes and API signatures to work with the newest Skia (see failed test).

**Comment by csmartdalton** [comment]
> Looks like the versions aren't compatible, we must've updated some includes and API signatures to work with the newest Skia (see failed test).

I hope it's just that we need https://github.com/rive-app/rive/pull/4100 first

**Comment by csmartdalton** [comment]
This also needs an update to the rive-cpp submodule. I'll wait for https://github.com/rive-app/rive/pull/4100 in order to make that final change

**Comment by csmartdalton** [comment]
Looks like tests are passing now that I've updated the rive-cpp submodule

**Review by zplata — APPROVED** [review]

**Pull request merged**
